apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: sample-remote
spec:
  forProvider:
    source: Remote
    module: git::https://github.com/dchinmay11/team-alpha.git/tree/dchinmay
  writeConnectionSecretToRef:
    namespace: default
    name: terraform-workspace-example-inline